import type { Metadata } from "next";

export const SITE_URL = "https://tylt.dev";
const SITE_NAME = "Tylt";

// The site-wide social card generated by src/app/opengraph-image.tsx. Restated
// explicitly per page because Next.js does not deep-merge `openGraph`/`twitter`
// into child routes — a page that sets either replaces the inherited block.
const OG_IMAGE = { url: "/opengraph-image", width: 1200, height: 630 } as const;

interface PageMetaInput {
  /** Page title — the " — Tylt" suffix is added for social cards. */
  title: string;
  /** Page description, shared across the description, OG, and Twitter tags. */
  description: string;
  /** Canonical path, e.g. "/work". Resolved against metadataBase. */
  path: string;
}

/**
 * Build a complete, page-specific metadata block: canonical URL plus fully
 * restated OpenGraph and Twitter cards (title, description, and the shared OG
 * image) so social shares are correct on every route.
 */
export function pageMetadata({
  title,
  description,
  path,
}: PageMetaInput): Metadata {
  const socialTitle = `${title} — ${SITE_NAME}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      url: path,
      title: socialTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

/**
 * Build a BreadcrumbList JSON-LD object from an ordered list of crumbs, so
 * search engines can render the page's position in the site hierarchy.
 */
export function breadcrumbLd(crumbs: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((crumb, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: crumb.name,
      item: `${SITE_URL}${crumb.path === "/" ? "" : crumb.path}`,
    })),
  };
}
